### **Types of Matrices**
Special matrices can be classified into various categories according to their distinctive mathematical properties. These matrices are often assigned specific names that reflect their defining characteristics or commemorate the mathematicians who first discovered, introduced, or systematically characterized them. The following presents a representative, though non-exhaustive, list of several important classes of special matrices, along with a brief description of their defining properties.

#### **Square and Rectangular Matrix**
A **square matrix** is a matrix that has an equal number of rows and columns. Thus, a matrix of size N × N is square; more generally, an M × N matrix is square if M = N. A matrix in which the number of rows and columns are unequal is called a **rectangular matrix**.

In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Square Matrices
A = np.random.randint(0, 9, size=(5,5))       # 5 x 5 Square Matrix of Random Integers
B = np.random.randn(4, 4)                     # 4 x 4 Square Matrix of Random Numbers

print("A =\n", A)
print(" ")
print("B =\n", B)

A =
 [[8 0 1 4 1]
 [5 8 5 2 5]
 [1 5 3 4 6]
 [5 4 8 3 0]
 [0 7 2 3 7]]
 
B =
 [[ 0.22063287 -0.72216554 -0.11575202 -0.40951145]
 [ 0.09888132 -2.42508543 -1.38329218 -0.08670563]
 [ 1.52093484  0.12177909  1.19299536 -1.79818957]
 [ 1.316393   -0.02462013  0.88804049 -1.35645291]]


In [3]:
# Rectangular Matrices
C = np.random.randint(0, 9, (2, 4))
D = np.random.randn(5, 2)

print("C =\n", C)
print(" ")
print("D =\n", D)

C =
 [[8 2 7 6]
 [8 1 1 6]]
 
D =
 [[ 0.99867258 -0.78489824]
 [ 0.02116482 -1.10245188]
 [-0.01632705 -0.07171631]
 [-1.68700891 -0.23282165]
 [-0.51364577 -0.31319104]]


#### **Symmetric Matrix**
A **symmetric matrix** is a square matrix that remains unchanged when reflected across its main diagonal. In other words, the entries above the main diagonal are mirror images of the corresponding entries below it. Formally, a matrix **A** is symmetric if it is equal to its transpose, that is, **$A = A^T$**. Note that only square matrices can be symmetric.

A matrix that does not satisfy the condition **$A = A^T$** is referred to as a **non-symmetric or asymmetric matrix**. In particular, every rectangular matrix is necessarily non-symmetric, since only square matrices can be equal to their transposes.

The most common way to create a symmetric matrix is to generate a random matrix and add it to its transpose.

In [4]:
# Create a random matrix
M = np.random.randint(-5, 5, size=(3,3))

# Make it Symmetric
S = M + M.T

print("Symmetric Matrix S:\n", S)
print(" ")
print("Transpose of S:\n", S.T)
print(" ")
# Verify
print("Is S Symmetric Matrix?", np.array_equal(S, S.T))

Symmetric Matrix S:
 [[-4  2  0]
 [ 2  2  0]
 [ 0  0 -4]]
 
Transpose of S:
 [[-4  2  0]
 [ 2  2  0]
 [ 0  0 -4]]
 
Is S Symmetric Matrix? True


The second approach for constructing a symmetric matrix involves using the **upper triangular** portion of a randomly generated matrix. First, a random matrix is generated, and its **upper triangular** part is extracted. This **upper triangular matrix** is then added to **its transpose**, resulting in a symmetric matrix.

In [5]:
# Create a Random Matrix
M = np.random.randint(1, 10, size=(4, 4))

# Make it Symmetric
S = np.triu(A) + np.triu(A, 1).T

print("Symmetric Matrix S:\n", S)
print(" ")
print("Transpose of S:\n", S.T)
print(" ")
# Verify
print("Is S Symmetric Matrix?", np.array_equal(S, S.T))

Symmetric Matrix S:
 [[8 0 1 4 1]
 [0 8 5 2 5]
 [1 5 3 4 6]
 [4 2 4 3 0]
 [1 5 6 0 7]]
 
Transpose of S:
 [[8 0 1 4 1]
 [0 8 5 2 5]
 [1 5 3 4 6]
 [4 2 4 3 0]
 [1 5 6 0 7]]
 
Is S Symmetric Matrix? True


#### **Skew-symmetric Matrix**
A **skew-symmetric matrix** is a square matrix in which the entries below the main diagonal are the negatives of the corresponding entries above the diagonal. Equivalently, a matrix **A** is **skew-symmetric** if its transpose is equal to its negative, that is, **$A^T=−A$**.

We can create a **skew-symmetric matrix** using the property **$A^T=−A$**.

In [6]:
# Create a Random Matrix
A = np.random.randint(1, 10, size=(4, 4))

# Create a Skew-symmetric Matrix
S = A - A.T

print("Skew-symmetric Matrix S:\n", S)
print(" ")
print("Transpose of S:\n", S.T)
print(" ")
# Verify
print("Is S skew-symmetric?", np.array_equal(S.T, -S))
print()

Skew-symmetric Matrix S:
 [[ 0  8  1  1]
 [-8  0 -3  2]
 [-1  3  0 -1]
 [-1 -2  1  0]]
 
Transpose of S:
 [[ 0 -8 -1 -1]
 [ 8  0  3 -2]
 [ 1 -3  0  1]
 [ 1  2 -1  0]]
 
Is S skew-symmetric? True



The zero entries along the main diagonal of a skew-symmetric matrix are a direct consequence of its defining property. Since a skew-symmetric matrix satisfies **$A^T=−A$**, each diagonal element must be equal to its own negative. The only number that satisfies this condition is zero, since **0 = −0**. Therefore, **every skew-symmetric matrix necessarily has zeros along its main diagonal**.

#### **Identity Matrix**
An **identity matrix** is a square matrix whose main diagonal consists entirely of 1s, while all other entries are 0s. It acts as the multiplicative identity for matrices, meaning that multiplying any compatible matrix by the identity matrix leaves it unchanged.

For an **n×n** identity matrix:
$$
I_n =
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{bmatrix}
$$

Thus for any compatible matrix A,

$$
AI_{n} = I_{n}A = A
$$


In [7]:
# Identity Matrices
I1 = np.eye(5, dtype=int)
I2 = np.eye(3)

print("I1 =\n", I1)
print(" ")
print("I2 =\n", I2)

I1 =
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
 
I2 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### **Zero Matrix**
A **zero matrix** is a matrix in which every entry is equal to zero. It can have any number of rows and columns and is commonly denoted by **0** or **$0_{m×n}$**. Intuitively, it serves as the additive identity for matrices, since adding a zero matrix to any matrix leaves the original matrix unchanged:
$$
A + 0 = 0 + A = A
$$

In [8]:
# Zero Matrices
Z1 = np.zeros(shape=(3,5), dtype=int)  # Rectangular Zero Matrix
Z2 = np.zeros((4,4))                   # Square Zero Matrix
Z3 = np.zeros((3,3), dtype=complex)    # Square Zero Matrix of Complex Datatype

print("Z1 =\n", Z1)
print(" ")
print("Z2 =\n", Z2)
print(" ")
print("Z3 =\n", Z3)

Z1 =
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
 
Z2 =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
Z3 =
 [[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


#### **Diagonal Matrix**
A **diagonal matrix** is a matrix, square or rectangular, in which **all entries outside the main diagonal are zero**. The entries on the main diagonal may be any numbers, including zero. In other words, the only positions where nonzero values can occur are along the main diagonal.

For example,

$$
D =
\begin{bmatrix}
d_1 & 0 & 0 \\
0 & d_2 & 0 \\
0 & 0 & d_3
\end{bmatrix}
$$

Thus, a diagonal matrix can be viewed as a matrix whose information is concentrated entirely along its main diagonal. The **identity matrix** and **zero matrix** are special cases of diagonal matrices.

In [9]:
# Diagonal Matrices
# 
# Create a Square Diagonal Matrix from a List of Numbers 
D1 = np.diag([3, 4, 0, 7])  # Square Diagonal Matrix with 3, 4, 0, and 7 as Diagonal Elements

# Extract the main Diagonal from a Matrix
M = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
               ])
v = np.diag(M)     # Extract the Main Diagonal from a Matrix as Vector
D2 = np.diag(v)    # Create a Digonal Matrix from the Extracted Vector

print("D1 =\n", D1)
print(" ")
print("D2 =\n", D2)

D1 =
 [[3 0 0 0]
 [0 4 0 0]
 [0 0 0 0]
 [0 0 0 7]]
 
D2 =
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


A **hollow matrix** is a matrix whose **main diagonal consists entirely of zeros, while its off-diagonal entries may be either zero or nonzero**. In other words, the defining characteristic of a hollow matrix is that all of its diagonal elements are zero. Every **skew-symmetric matrix** is necessarily **hollow**, since its diagonal elements must equal their own negatives and are therefore zero. Hollow matrices also arise naturally in applications such as distance matrices, where each diagonal entry is zero because the distance from any node to itself is zero.

#### **Triangular Matrices**
A **triangular matrix** is a matrix in which all entries on one side of the main diagonal are zero. Depending on which side contains the zeros, it is classified as either an **upper triangular** or a **lower triangular** matrix. This concept can be applied to both square and rectangular matrices, although some texts reserve the term triangular matrix specifically for square matrices.

An **upper triangular** matrix has **zeros below** the main diagonal, while the entries on and above the diagonal may be nonzero.

A **lower triangular** matrix has **zeros above** the main diagonal, while the entries on and below the diagonal may be nonzero.

For example, a rectangular **upper triangular** matrix can be written as

$$
U=
\begin{bmatrix}
u_{11} & u_{12} & u_{13} & u_{14}\\
0 & u_{22} & u_{23} & u_{24}\\
0 & 0 & u_{33} & u_{34}
\end{bmatrix}
$$


whereas a rectangular **lower triangular** matrix can be written as

$$
L=
\begin{bmatrix}
\ell_{11} & 0 & 0\\
\ell_{21} & \ell_{22} & 0\\
\ell_{31} & \ell_{32} & \ell_{33}\\
\ell_{41} & \ell_{42} & \ell_{43}
\end{bmatrix}
$$


Intuitively, the zero entries form a triangular region on one side of the main diagonal, which gives these matrices their name. Triangular matrices are particularly important in linear algebra because their structure simplifies operations such as solving systems of equations and computing determinants.


In [10]:
# Create Triangular Matrix from Full Matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)

print("S =\n", S)
print(" ")
print("U =\n", U)
print(" ")
print("L =\n", L)

S =
 [[ 0.57726719 -1.58901811  1.27701849  0.56510172 -0.37126819]
 [ 0.1339237  -1.2475895  -1.09699666  2.11127475 -1.35381838]
 [-0.82829752  1.27433176  0.37827818  0.24488598  1.70375171]
 [ 0.50064995  0.5969767   1.266804    1.00382513 -0.07354838]
 [ 0.62720112  1.2405035  -0.2054858  -0.29281858  0.45624756]]
 
U =
 [[ 0.57726719 -1.58901811  1.27701849  0.56510172 -0.37126819]
 [ 0.         -1.2475895  -1.09699666  2.11127475 -1.35381838]
 [ 0.          0.          0.37827818  0.24488598  1.70375171]
 [ 0.          0.          0.          1.00382513 -0.07354838]
 [ 0.          0.          0.          0.          0.45624756]]
 
L =
 [[ 0.57726719  0.          0.          0.          0.        ]
 [ 0.1339237  -1.2475895   0.          0.          0.        ]
 [-0.82829752  1.27433176  0.37827818  0.          0.        ]
 [ 0.50064995  0.5969767   1.266804    1.00382513  0.        ]
 [ 0.62720112  1.2405035  -0.2054858  -0.29281858  0.45624756]]


#### **Agumented Matrix**
An **augmented matrix** is a matrix formed by appending one or more columns to a given matrix, typically to incorporate additional information associated with the original matrix. In linear algebra, it is most commonly used to represent a system of linear equations by appending the column of constants to its coefficient matrix. For example, the system

$$
\begin{aligned}
2x+y &= 5,\\
x+3y &= 7
\end{aligned}
$$

can be represented by the augmented matrix

$$
\left[
\begin{array}{cc|c}
2 & 1 & 5 \\
1 & 3 & 7
\end{array}
\right]
$$


Here, the first two columns contain the coefficients of the variables, while the final column contains the corresponding constants.

In [11]:
# Matrices can be augmented only if they have the same number of rows
A1 = np.random.randint(-5, 5, size=(3, 2))
A2 = np.random.randint(0, 9, (3, 4))
# Augmentation of Matrices
M_Augment = np.concatenate((A1, A2), axis=1)

print("A1 =\n", A1)
print(" ")
print("A2 =\n", A2)
print(" ")
print("M_Augment =\n", M_Augment)
print(" ", "\n")

A1 =
 [[-4  4]
 [ 4  2]
 [ 0 -3]]
 
A2 =
 [[3 5 8 6]
 [8 3 3 0]
 [2 6 4 4]]
 
M_Augment =
 [[-4  4  3  5  8  6]
 [ 4  2  8  3  3  0]
 [ 0 -3  2  6  4  4]]
  



**"Augmenting"** is called **concatenation** in `Python`.

#### Dense and Sparse Matrices
A **dense matrix** is a matrix in which **most of its entries are nonzero**. In other words, the numerical information is distributed throughout the matrix, with relatively few zero entries.

A **sparse matrix**, in contrast, is a matrix in which **most of its entries are zero**. Only a relatively small number of elements contain nonzero values. Sparse matrices commonly arise in applications where each element or variable interacts with only a limited number of others, such as networks, graphs, and large systems of equations.

For example, the following is a dense matrix:

$$
A=
\begin{bmatrix}
2 & 5 & 1\\
4 & 3 & 7\\
6 & 8 & 9
\end{bmatrix}
$$


where every entry is nonzero. In comparison,

$$
B=
\begin{bmatrix}
5 & 0 & 0 & 0\\
0 & 3 & 0 & 0\\
0 & 0 & 7 & 0\\
0 & 0 & 0 & 2
\end{bmatrix}
$$

is sparse because the majority of its entries are zero.

In practice, a matrix is considered sparse when its zero entries are sufficiently numerous that storing and processing only the nonzero entries can provide computational or memory advantages.