### **Addition of Matrices**
The **addition of two matrices** is the operation of adding their corresponding elements. Two matrices can be added **only when they have the same order**, i.e., the same number of rows and columns.

If

$$
A=[a_{ij}]_{m\times n}
\quad\text{and}\quad
B=[b_{ij}]_{m\times n},
$$

then their sum is defined as

$$
A+B=[a_{ij}+b_{ij}]_{m\times n}.
$$

In simple terms, **matrix addition means adding the elements that occupy the same position in the two matrices**.<br>
For example, the element in the first row and first column of A is added to the element in the first row and first column of B, and so on.<br>
Consider the matrices

$$
A=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
1 & 6\\
2 & 3
\end{bmatrix}.
$$

Both matrices have two rows and two columns, so they can be added. <br>
We add their corresponding elements:

$$
A+B=
\begin{bmatrix}
2+1 & 3+6\\
4+2 & 5+3
\end{bmatrix}.
$$

Therefore,

$$
A+B=
\begin{bmatrix}
3 & 9\\
6 & 8
\end{bmatrix}.
$$

Thus, matrix addition is essentially **ordinary addition performed position-by-position**, while preserving the arrangement of the elements.

#### **Basic Properties of Matrix Addition**
Suppose **A**, **B**, and **C** are matrices of the same order.
##### **1. Closure Property**
   The **closure property** states that the sum of two matrices of the same order is also a matrix of that same order.
   If A and B are both matrices of order m×n, then

   $$
   A+B
   $$

is also a matrix of order m×n. In other words, matrix addition does not change the dimensions of the matrices being added.

##### **2. Commutative Property**
The **commutative property** states that the order in which two matrices are added does not affect the result.

$$
A+B=B+A.
$$

For example, adding A to B gives the same result as adding B to A. This property follows from the commutative property of ordinary numbers, since corresponding elements are simply added.

##### **3. Associative Property**
The **associative property** states that when adding three matrices, the way in which they are grouped does not affect the result.

$$
(A+B)+C=A+(B+C).
$$

This means that we can first add A and B, and then add C, or first add B and C, and then add A. The final matrix will be the same.

##### **4. Additive Identity Property**

The zero matrix acts as the additive identity.

A zero matrix is a matrix in which every element is zero. If O represents the zero matrix, then

$$
A+O=O+A=A.
$$

Thus, adding a zero matrix to any matrix leaves the original matrix unchanged. For example,

$$
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
+
\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}
=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}.
$$

##### **5. Additive Inverse Property**

For every matrix A, there exists a matrix called its additive inverse, denoted by −A, such that their sum is the zero matrix.

$$
A+(-A)=(-A)+A=O.
$$

The additive inverse of a matrix is obtained by changing the sign of every element. For example, if

$$
A=
\begin{bmatrix}
2 & -3\\
4 & 5
\end{bmatrix},
$$

then its additive inverse is

$$
-A=
\begin{bmatrix}
-2 & 3\\
-4 & -5
\end{bmatrix}.
$$

Therefore,

$$
A+(-A)=
\begin{bmatrix}
2 & -3\\
4 & 5
\end{bmatrix}
+
\begin{bmatrix}
-2 & 3\\
-4 & -5
\end{bmatrix}
=
\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}
$$

These properties make matrix addition behave very similarly to ordinary addition of numbers, with the additional requirement that the matrices must have the **same order**.


In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Create three Matrices of Random Integers
A = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix
B = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix
C = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix

print("A =\n", A)
print(" ")
print("B =\n", B)
print(" ")
print("C =\n", C)

A =
 [[6 4 4]
 [8 3 1]
 [1 7 0]]
 
B =
 [[1 0 4]
 [4 4 3]
 [4 5 8]]
 
C =
 [[0 6 8]
 [3 6 4]
 [7 8 6]]


In [3]:
# Closure Property of Matrix Addition
D = A + B            # D will also be a 3 x 3 Matrix

print("D =\n", D)

D =
 [[ 7  4  8]
 [12  7  4]
 [ 5 12  8]]


In [4]:
# Commutative Property of Matrix Addition
APlusB = A + B
BPlusA = B + A

print("APlusB =\n", APlusB)
print(" ")
print("BPlusA =\n", BPlusA)

APlusB =
 [[ 7  4  8]
 [12  7  4]
 [ 5 12  8]]
 
BPlusA =
 [[ 7  4  8]
 [12  7  4]
 [ 5 12  8]]


In [5]:
# Associativity Property of Matrix Addition
APlusB = A + B
APlusBPlusC = APlusB + C

BPlusC = B + C
BPlusCPlusA = BPlusC + A

print("APlusBPlusC =\n", APlusBPlusC)
print(" ")
print("BPlusCPlusA =\n", BPlusCPlusA)

APlusBPlusC =
 [[ 7 10 16]
 [15 13  8]
 [12 20 14]]
 
BPlusCPlusA =
 [[ 7 10 16]
 [15 13  8]
 [12 20 14]]


In [6]:
# Additive Identity
Z = np.zeros((3,3), dtype=int)       # 3 x 3  Zeros Matrix
APlusZ = A + Z

print("A =\n", A)
print(" ")
print("APlusZ =\n", APlusZ)

A =
 [[6 4 4]
 [8 3 1]
 [1 7 0]]
 
APlusZ =
 [[6 4 4]
 [8 3 1]
 [1 7 0]]


In [7]:
# Additive Inverse
NegA = -1 * A
AddInv = A + NegA

print("addInv =\n", AddInv)

addInv =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
