### **Subtraction of Matrices**
The **subtraction of two matrices** is the operation of subtracting the corresponding elements of one matrix from another matrix. Two matrices can be subtracted **only if they have the same order**, meaning they must have the same number of rows and columns.

If

$$
A=[a_{ij}]_{m\times n}
\quad\text{and}\quad
B=[b_{ij}]_{m\times n},
$$

then the difference of A and B is defined as

$$
A-B=[a_{ij}-b_{ij}]_{m\times n}.
$$

In simple terms, **matrix subtraction means subtracting the elements that occupy the same position in the two matrices**. For example, the element in the first row and first column of B is subtracted from the corresponding element in A, and the same process is repeated for all corresponding positions.<br>
Consider the matrices

$$
A=
\begin{bmatrix}
8 & 7\\
6 & 5
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
3 & 2\\
1 & 4
\end{bmatrix}.
$$

Both matrices have two rows and two columns, so they can be subtracted. <br>
We subtract their corresponding elements:

$$
A-B=
\begin{bmatrix}
8-3 & 7-2\\
6-1 & 5-4
\end{bmatrix}.
$$

Therefore,

$$
A-B=
\begin{bmatrix}
5 & 5\\
5 & 1
\end{bmatrix}.
$$

Thus, matrix subtraction is essentially **ordinary subtraction performed position-by-position**, while preserving the arrangement of the elements.

#### **Subtraction as Addition of the Additive Inverse**

Matrix subtraction can also be understood in terms of matrix addition.

The difference between two matrices A and B can be written as the addition of A and the additive inverse of B:

$$
A-B=A+(-B).
$$

This is an important relationship because it shows that **matrix subtraction is based on matrix addition and additive inverses**. For example, if

$$
B=
\begin{bmatrix}
3 & 2\\
1 & 4
\end{bmatrix},
$$

Then,

$$
-B=
\begin{bmatrix}
-3 & -2\\
-1 & -4
\end{bmatrix}.
$$

Therefore,

$$
A-B=A+(-B).
$$


#### **Basic Properties of Matrix Subtraction**
Suppose **A**, **B**, and **C** are matrices of the same order.
##### **1. Closure Property**
   The **closure property** states that subtracting two matrices of the same order produces another matrix of that same order.
   If A and B are both matrices of order m×n, then

   $$
   A-B
   $$

is also a matrix of order m × n. Therefore, matrix subtraction is **closed** over matrices of the same order.

##### **2. Subtraction is not Commutative**
Unlike matrix addition, matrix subtraction is generally **not commutative**. In general,

$$
A-B\neq B-A.
$$

In fact, we have

$$
A-B=-(B-A).
$$

For example, let

$$
A=
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}.
$$

Then,

$$
A-B=
\begin{bmatrix}
4 & 4\\
4 & 4
\end{bmatrix},
$$

whereas,

$$
B-A=
\begin{bmatrix}
-4 & -4\\
-4 & -4
\end{bmatrix}.
$$

Hence,

$$
A-B\neq B-A.
$$

This is one of the most important differences between **matrix addition** and **matrix subtraction**.

##### **3. Subtraction is Not Associative**
Matrix subtraction is generally **not associative**. In general,

$$
(A-B)-C\neq A-(B-C).
$$

For example, consider three matrices A, B, and C. The expression on the left means:

$$
(A-B)-C,
$$

while the expression on the right means:

$$
A-(B-C).
$$

These expressions generally produce different results. Therefore,

$$
(A-B)-C\neq A-(B-C).
$$

This is another important difference between matrix addition and matrix subtraction.

##### **4. Subtraction of the Zero Matrix**

Subtracting the zero matrix from a matrix leaves the matrix unchanged.

If O is the zero matrix, then

$$
A-O=A.
$$

For example,

$$
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
-
\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}
=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}.
$$

However, subtracting a matrix from the zero matrix gives its additive inverse:

$$
O-A=-A.
$$


##### **5. Subtraction of a Matrix from Itself**
Any matrix subtracted from itself gives the zero matrix.

$$
A-A=O.
$$

For example,

$$
\begin{bmatrix}
4 & 7\\
2 & 9
\end{bmatrix}
-
\begin{bmatrix}
4 & 7\\
2 & 9
\end{bmatrix}
=
\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}.
$$

This property follows because every element is subtracted from itself.

In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Create three Matrices of Random Integers
A = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix
B = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix
C = np.random.randint(0, 9, (3,3))        # 3 x 3 Matrix

print("A =\n", A)
print(" ")
print("B =\n", B)
print(" ")
print("C =\n", C)

A =
 [[7 5 7]
 [2 1 6]
 [0 4 8]]
 
B =
 [[5 3 4]
 [2 4 6]
 [8 8 3]]
 
C =
 [[7 2 2]
 [3 7 6]
 [4 0 3]]


In [3]:
# Subtraction of Matrix A & B
S1 = A - B
print("S1 =\n", S1)

S1 =
 [[ 2  2  3]
 [ 0 -3  0]
 [-8 -4  5]]


In [4]:
# Subtraction as Addition of the Additive Inverse
AddInvOfB = -1 * B
S2 = A + AddInvOfB
print("S1 =\n", S1)

S1 =
 [[ 2  2  3]
 [ 0 -3  0]
 [-8 -4  5]]


In [5]:
# Closure Property of Matrix Subtraction
D = A - B            # D will also be a 3 x 3 Matrix

print("D =\n", D)

D =
 [[ 2  2  3]
 [ 0 -3  0]
 [-8 -4  5]]


In [6]:
# Subtraction is Not Commutative
AMinusB = A - B
BMinusA = B - A

print("AMinusB =\n", AMinusB)
print(" ")
print("BMinusA =\n", BMinusA)
print(" ")
# Verfiy the property
print("AMinusB = BMinusA: ", np.array_equal(AMinusB, BMinusA))

AMinusB =
 [[ 2  2  3]
 [ 0 -3  0]
 [-8 -4  5]]
 
BMinusA =
 [[-2 -2 -3]
 [ 0  3  0]
 [ 8  4 -5]]
 
AMinusB = BMinusA:  False


In [7]:
# Subtraction is Not Associative
AMinusB = A - B
LHS = AMinusB - C

BMinusC = B - C
RHS = A - BMinusC

print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)
print(" ")
# Verify Subtraction is Not Associative
print("LHS = RHS:", np.array_equal(LHS, RHS))

LHS =
 [[ -5   0   1]
 [ -3 -10  -6]
 [-12  -4   2]]
 
RHS =
 [[ 9  4  5]
 [ 3  4  6]
 [-4 -4  8]]
 
LHS = RHS: False


In [8]:
# Subtraction of the Zero Matrix
Z = np.zeros((3,3), dtype=int)       # 3 x 3  Zeros Matrix
AMinusZ = A - Z

print("A =\n", A)
print(" ")
print("AMinusZ =\n", AMinusZ)
print(" ")
# Verify Subtraction of Zeros Matrix
print("A = AMinusZ:", np.array_equal(A, AMinusZ))

A =
 [[7 5 7]
 [2 1 6]
 [0 4 8]]
 
AMinusZ =
 [[7 5 7]
 [2 1 6]
 [0 4 8]]
 
A = AMinusZ: True


In [9]:
# Subtraction of a Matrix from Itself is Zero Matrix
R = A - A

print("R =\n", R)
print(" ")
# Verify Subtraction of a Matrix from Itself is Zero Matrix
print("Z = R:", np.array_equal(Z, R))

R =
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
 
Z = R: True
