### **Scalar Multiplication of a Matrix**
**Scalar multiplication** is the operation of multiplying every element of a matrix by a single number called a **scalar**. If A is a matrix and *k* is a scalar, then the scalar multiplication of A by *k* is written as:

$$
kA=[ka_{ij}]_{m\times n}.
$$

In simple terms, **multiply every element of the matrix by the scalar**. The order or dimensions of the matrix do not change.

Consider the matrix

$$
A=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
$$

and let the scalar be 3. We multiply every element of A by 3:

$$
3A=
3
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
=
\begin{bmatrix}
3(2) & 3(3)\\
3(4) & 3(5)
\end{bmatrix}.
$$

Therefore,

$$
3A=
\begin{bmatrix}
6 & 9\\
12 & 15
\end{bmatrix}.
$$

Thus, scalar multiplication **changes the values of the elements but does not change the dimensions of the matrix**.

In general, if **A** is,

$$
A=
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

and *k* is a scalar, then

$$
kA=
\begin{bmatrix}
ka_{11} & ka_{12} & \cdots & ka_{1n}\\
ka_{21} & ka_{22} & \cdots & ka_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
ka_{m1} & ka_{m2} & \cdots & ka_{mn}
\end{bmatrix}.
$$

Thus, the simple rule is to multiply every element of the matrix by the scalar.


In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Matrix Dimensions
m = 3
n = 4

# Matrix of m x n random integers
A = np.random.randint(1, 9, (m,n))

# Scalar k
k = 3

# Scalar-matrix Multipliction 
kTimesA = k * A

print("A =\n", A)
print(" ")
print("kTimesA =\n", kTimesA)

A =
 [[4 7 2 1]
 [5 6 6 3]
 [6 5 5 2]]
 
kTimesA =
 [[12 21  6  3]
 [15 18 18  9]
 [18 15 15  6]]


<br>

#### **Basic Properties of Scalar Multiplication**
Let **A** and **B** be matrices of the same order, and let *k* and *l* be scalars.
##### **1. Closure Property**
If A is an m×n matrix and *k* is a scalar, then *k*A is also an m×n matrix.

$$
A\in\mathbb{R}^{m\times n}
\quad\Longrightarrow\quad
kA\in\mathbb{R}^{m\times n}.
$$

Therefore, scalar multiplication **does not change the order of a matrix**.

In [3]:
# Scalar multiplication does not change matrix order
A = np.random.randint(1, 9, (2,2))   # 2 x 2 matrix of random integers
# Scalar k
k = 2

kTimesA = k * A

print("Order of A =", A.shape)
print("Order of kTimesA =", kTimesA.shape)
print(" ")
print("A =\n", A)
print(" ")
print("kTimesA =\n", kTimesA)

Order of A = (2, 2)
Order of kTimesA = (2, 2)
 
A =
 [[5 4]
 [5 6]]
 
kTimesA =
 [[10  8]
 [10 12]]


<br>

##### **2. Commutative Property of Scalar Multiplication**
Scalar multiplication has a commutative property because the order in which two scalars are multiplied does not affect the result.

For scalars *k* and *l*,

$$
(kl)A=(lk)A.
$$

Since ordinary scalar multiplication is commutative,

$$
kl=lk.
$$

Therefore,

$$
(kl)A=(lk)A.
$$

There is another commonly used statement involving a scalar and a matrix:

$$
kA=Ak.
$$

This means that multiplying a matrix A by a scalar *k* from the left gives the same result as multiplying it from the right. For example,

$$
3
\begin{bmatrix}
2 & 4\\
1 & 5
\end{bmatrix}
=
\begin{bmatrix}
2 & 4\\
1 & 5
\end{bmatrix}
3.
$$

Both sides give,

$$
\begin{bmatrix}
6 & 12\\
3 & 15
\end{bmatrix}.
$$

Thus, **scalar multiplication is commutative**:

$$
\boxed{kA=Ak}.
$$

This is different from ordinary matrix multiplication, where in general AB≠BA.


In [4]:
# Scalar multiplication is commutative
A = np.random.randint(1, 9, (m,n))        # Matrix of m x n random integers

# Scalars k and l
alpha = 2
k = 3

# (alpha * k) * A = (k * alpha) * A
LHS = (alpha * k) * A
RHS = (k * alpha) * A

print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)
print(" ")

# k * A = A * k
LHS = k * A
RHS = A * k
print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)

LHS =
 [[48 42  6 30]
 [ 6 30 36 42]
 [ 6 48 18 30]]
 
RHS =
 [[48 42  6 30]
 [ 6 30 36 42]
 [ 6 48 18 30]]
 
LHS =
 [[24 21  3 15]
 [ 3 15 18 21]
 [ 3 24  9 15]]
 
RHS =
 [[24 21  3 15]
 [ 3 15 18 21]
 [ 3 24  9 15]]


<br>

##### **3. Distributive Property over Matrix Addition**
Scalar multiplication distributes over the addition of matrices.

$$
k(A+B)=kA+kB.
$$

For example, if

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix},
$$

Then,

$$
2(A+B)=2A+2B.
$$

The important idea is that the scalar can be distributed across the matrix addition.


In [5]:
# Scalar multiplication distributes over the addition of matrices
A = np.random.randint(1, 9, (m, n))
B = np.random.randint(1, 9, (m, n))

# Scalar k
k = 2

# k(A + B) = kA + kB
LHS = k * (A + B)
RHS = k*A + k*B

print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)
print(" ")
# Verify
print("LHS == RHS:", np.array_equal(LHS, RHS))

LHS =
 [[10 26  8 20]
 [26 20 18 12]
 [ 6 24 30 18]]
 
RHS =
 [[10 26  8 20]
 [26 20 18 12]
 [ 6 24 30 18]]
 
LHS == RHS: True


<br>

##### **4. Distributive Property over Scalar Addition**
Scalar multiplication also satisfies the distributive property with respect to scalar addition:

$$
(k+l)A=kA+lA.
$$

For example,

$$
(2+3)A=2A+3A.
$$

Both sides produce the same matrix.


In [6]:
# Matrix multiplication distributes over Scalar addition
A = np.random.randint(1, 9, (m, n))

# Scalars alpha and k
alpha = 3
k = 2

# (alpha + k) = alpha*A + k*A
LHS = (alpha + k) * A
RHS = alpha*A + k*A

print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)
print(" ")
# Verify
print("LHS == RHS:", np.array_equal(LHS, RHS))

LHS =
 [[10 30 15 20]
 [35 10 20 40]
 [ 5 25 30  5]]
 
RHS =
 [[10 30 15 20]
 [35 10 20 40]
 [ 5 25 30  5]]
 
LHS == RHS: True


<br>

##### **5. Associative Property of Scalar Multiplication**
When multiple scalars are multiplied with a matrix, the grouping of the scalar multiplication does not matter.

$$
k(lA)=(kl)A.
$$

For example,

$$
2(3A)=(2\times3)A=6A.
$$

Thus, we can multiply the scalars first or multiply the matrix by one scalar first.



In [7]:
# Grouping of the scalar multiplication does not matter
A = np.random.randint(1, 9, (2, 2))

# Scalars alpha and k
alpha = 3
k = 2

# alpha * (k*A) = (alpha*k) * A
LHS = alpha * (k*A)
RHS = (alpha*k) * A

print("LHS =\n", LHS)
print(" ")
print("RHS =\n", RHS)
print(" ")
# Verify
print("LHS == RHS:", np.array_equal(LHS, RHS))

LHS =
 [[42 18]
 [18 30]]
 
RHS =
 [[42 18]
 [18 30]]
 
LHS == RHS: True


<br>

##### **6. Multiplication by the Scalar 1**
Multiplying a matrix by 1 leaves the matrix unchanged.

$$
1A=A.
$$

For example,

$$
1
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}.
$$

Therefore, 1 acts as the **multiplicative identity** for scalar multiplication.



In [8]:
# Multiplying by 1 leaves the matrix unchanged
A = np.random.randint(1, 9, (2,2))
oneTimesA = 1 * A

print("A =\n", A)
print("")
print("oneTimesA =\n", oneTimesA)

A =
 [[4 5]
 [6 4]]

oneTimesA =
 [[4 5]
 [6 4]]


<br>

##### **7. Multiplication by the Scalar 0**
Multiplying any matrix by zero produces the zero matrix.

$$
0A=O.
$$

For example,

$$
0
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
=
\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}.
$$


In [9]:
# Multiplying by zero produces Zeros matrix
A = np.random.randint(1, 9, (2,2))
zeroTimesA = 0 * A

print("A =\n", A)
print("")
print("zeroTimesA =\n", zeroTimesA)

A =
 [[4 2]
 [6 7]]

zeroTimesA =
 [[0 0]
 [0 0]]
