### **Shifting Matrix**
**Matrix shifting** is an operation that combines matrix addition with scalar multiplication. To shift a square matrix **A**, a scalar multiple of the identity matrix is added to it:

$$
\widetilde{A}=A+\lambda I.
$$

The resulting matrix $\widetilde{A}$ is called the shifted matrix. Since the identity matrix contains nonzero entries only on its main diagonal, shifting changes only the diagonal elements of A, while leaving all off-diagonal elements unchanged.

In [10]:
# Import Numpy Module
import numpy as np

In [11]:
# Matrix Dimensions
m = 4
n = 4

# Matrix of m x n random integers
A = np.random.randint(1, 9, (m,n))

# Identity Matrix
I = np.eye(4)

# Scalar k
k = 0.3

A_Tilde = A + k * I

print("A =\n", A)
print(" ")
print("A_Tilde =\n", A_Tilde)

A =
 [[4 8 3 8]
 [5 1 1 8]
 [6 1 7 8]
 [6 1 5 4]]
 
A_Tilde =
 [[4.3 8.  3.  8. ]
 [5.  1.3 1.  8. ]
 [6.  1.  7.3 8. ]
 [6.  1.  5.  4.3]]


<br>

An important consequence of shifting is that it can eliminate certain redundancies in a matrix. For instance, if two rows or columns of the original matrix are identical, adding **λI** can make them distinct because the shift affects different diagonal positions.

In [13]:
# Matrix of 3 x 3 random integers
A = np.array([
    [3, 4, 1],
    [3, 4, 1],
    [5, 7, 2]
])

# Identity Matrix
I = np.eye(3)

# Scalar k
k = 0.1

A_Tilde = A + k * I

print("A =\n", A)
print(" ")
print("A_Tilde =\n", A_Tilde)

A =
 [[3 4 1]
 [3 4 1]
 [5 7 2]]
 
A_Tilde =
 [[3.1 4.  1. ]
 [3.  4.1 1. ]
 [5.  7.  2.1]]


<br>

The magnitude of the shift determines how closely the shifted matrix resembles the original matrix. When ***λ*** is close to zero, the change in **A** is small. In particular, when ***λ = 0***, the shifted matrix is identical to the original matrix:

$$
\lambda=0\quad\Longrightarrow\quad\widetilde{A}=A.
$$

Therefore, in practical applications, ***λ*** is generally selected to be **as small as possible while still being sufficiently large to satisfy the requirements of the problem**.

In [19]:
# Matrix of 3 x 3 random integers
A = np.array([
    [2, 4, 1],
    [7, 5, 0],
    [9, 2, 3]
])

# Identity Matrix
I = np.eye(3)

# Scalar k
k = 0

A_Tilde = A + k * I

print("A =\n", A)
print(" ")
print("A_Tilde =\n", A_Tilde)

A =
 [[2 4 1]
 [7 5 0]
 [9 2 3]]
 
A_Tilde =
 [[2. 4. 1.]
 [7. 5. 0.]
 [9. 2. 3.]]
