### **Matrix Diagonal**
The **diagonal of a matrix** is the sequence of elements that extends from the **top-left corner toward the bottom-right corner**. These elements have the **same row and column number**. For example,

$$
A =
\begin{bmatrix}
\boxed{2} & 5 & 7 \\
3 & \boxed{4} & 1 \\
6 & 8 & \boxed{9}
\end{bmatrix}
$$

The diagonal elements are extracted and placed into a **vector**:

$$
v = \operatorname{diag}(A) =
\begin{bmatrix}
2 \\
4 \\
9
\end{bmatrix}
$$

Thus, the diagonal of matrix **A** is represented by the vector **v**.

A diagonal can be extracted from **both square and rectangular matrices**. For example, consider the ($2\times4$) rectangular matrix:

$$
B =
\begin{bmatrix}
\boxed{1} & 2 & 3 & 4 \\
5 & \boxed{6} & 7 & 8
\end{bmatrix}
$$

Its diagonal elements are extracted into a vector:

$$
v = \operatorname{diag}(B) =
\begin{bmatrix}
1 \\
6
\end{bmatrix}
$$

Notice that the diagonal stops when either the rows or the columns run out.

So, for an $M\times N$ matrix **A**, the diagonal can be extracted using:

$$
v = \operatorname{diag}(A)
$$

where each element of the vector **v** is given by:

$$
v_i = a_{i,i}, \qquad i \in \{1,2,\ldots,\min(M,N)\}
$$

Here:

- **M** = number of rows in the matrix.
- **N** = number of columns in the matrix.
- **$a_{i,i}$** = the matrix element at row *i*, column *i*.
- $min(M,N)$ determines how many diagonal elements can be extracted.

Thus, the diagonal vector has exactly $min(M,N)$ elements.

**In simple terms**: diag(A) extracts the elements where the **row index and column index are the same** and places them into a **vector**.

In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Create a 4 x 4 Matrix of random integers
A = np.round(5 * np.random.randn(4, 4))

# Two ways of using the Numpy diag() function
d = np.diag(A)    # Input is matrix, Output is Extracted Diagonal Vector from matrix
D = np.diag(d)    # Input is vector, output is a Constructed Diagonal Matrix from vector

print("A =\n", A)
print(" ")
print("d =\n", d)
print(" ")
print("D =\n", D)

A =
 [[ 3.  2. -3.  3.]
 [-4.  4.  7.  4.]
 [-9. -2. -4.  7.]
 [-2. -1. -8. -1.]]
 
d =
 [ 3.  4. -4. -1.]
 
D =
 [[ 3.  0.  0.  0.]
 [ 0.  4.  0.  0.]
 [ 0.  0. -4.  0.]
 [ 0.  0.  0. -1.]]


In [3]:
# Diagonal of Rectangular Matrix
B = np.round(5 * np.random.randn(6,2))    # Create a 6 x 2 Matrix of random integers

# Extract diagonal from rectangular matrix
v = np.diag(B)

print("B =\n", B)
print(" ")
print("v =\n", v)

B =
 [[-3.  4.]
 [ 7. -1.]
 [ 6. -3.]
 [ 6. -6.]
 [ 5.  8.]
 [-8. -1.]]
 
v =
 [-3. -1.]


### **Matrix Trace**
The **trace** of a square matrix is a scalar quantity obtained by summing the elements along its main diagonal. In other words, the trace provides a single numerical value obtained by **summing the diagonal entries of the matrix**. For a square matrix $A \in \mathbb{R}^{M \times M}$, the trace, denoted by $\operatorname{tr}(A)$, is defined as:

$$
\operatorname{tr}(A) = \sum_{i=1}^{M} a_{i,i}
$$

where $a_{i,i}$ represents the $i$-th diagonal element of the $M \times M$ matrix $A$.

The **trace operation** has two important applications in machine learning. First, it can be used to compute the **Frobenius norm** of a matrix, which provides a measure of the overall magnitude of the matrix.<br>
Second, the trace can be used to quantify the **distance between two matrices**, allowing their similarity or difference to be measured.

It is important to note that the trace is **defined only for square matrices**.

In [4]:
# Create a 4 x 4 Square Matrix of random integers
M = np.round(5 * np.random.randn(4,4))

# Method:1 Trace of Square Matrix using sum() and diag() functions
tr1 = np.sum(np.diag(M))

print("M =\n", M)
print(" ")
print("tr1 =\n", tr1)

M =
 [[ -5.  -3.   4.  -4.]
 [ -7.   5.  -6.  -9.]
 [  6.  -1.  -1.  -9.]
 [  1.  -1. -14.  -4.]]
 
tr1 =
 -5.0


In [5]:
# Method:2 Trace of Square Matrix using trace() function
tr2 = np.sum(np.diag(M))

print("tr2 =\n", tr2)

tr2 =
 -5.0
