### **Broadcasting Matrix Arithmetic**
**Broadcasting** is a mechanism that allows arithmetic operations to be performed between arrays or matrices of different shapes by **automatically extending the smaller array** to match the shape of the larger one.

Intuitively, broadcasting means that when two arrays have compatible dimensions, the smaller array is **conceptually repeated** along the necessary dimensions so that the operation can be carried out element by element. The smaller array is not necessarily copied in memory; the repetition is mainly a way of understanding how the operation is performed.

For example, consider a matrix **A** and a vector **b**:

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix},
\qquad
b =
\begin{bmatrix}
10 & 20 & 30
\end{bmatrix}
$$

Here, **A** has shape $2 \times 3$, while **b** has shape $1 \times 3$. When adding them, the vector **b** is broadcast across the rows of **A**:

$$
A + b =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
+
\begin{bmatrix}
10 & 20 & 30 \\
10 & 20 & 30
\end{bmatrix}
=
\begin{bmatrix}
11 & 22 & 33 \\
14 & 25 & 36
\end{bmatrix}
$$

Thus, broadcasting allows operations such as addition, subtraction, multiplication, and division to be performed between arrays of compatible but **different** shapes, without explicitly constructing the repeated array.

In [1]:
# Import numpy module
import numpy as np

In [5]:
# Create a matrix of integers
M = np.reshape(np.arange(1, 13), (3,4), 'F')   # F=Column Major Order, C=Row Major Order

# Create two vectors
r = np.array([10, 20, 30, 40])        # Row Vector
c = np.array([[100], [200], [300]])   # Column Vector

print("M =\n", M)
print()
print("r =\n", r)
print()
print("c =\n", c)

M =
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

r =
 [10 20 30 40]

c =
 [[100]
 [200]
 [300]]


In [4]:
# Broadcast Addition on the Rows
print("M + r =\n", M + r)
print()

M + r =
 [[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]



In [6]:
# Broadcast Addition on the Columns
print("M + c =\n", M + c)
print()

M + c =
 [[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]

