### Code Challenge - Is Matrix-Scalar Multiplication a Linear Operation
Test for some random MxN matrices whether **s(A + B) = sA + sB** 

In [1]:
# Import Numpy module
import numpy as np

In [2]:
# Create Matrix Sizes
m = 7
n = 5

In [3]:
# Create two random matrices of m x n
A = np.random.randn(m, n)
B = np.random.randn(m, n)

In [5]:
# Create a random scalar
s = np.random.randn()

In [6]:
# Compute L.H.S of the Equation
resL = s * (A + B)
print(resL)

[[ 0.23092947 -0.45566922  0.73235297 -0.54789103  0.18954118]
 [-0.10380992  0.9350587  -0.22498698 -0.67292268 -0.33865129]
 [ 0.95555409  0.89876608 -0.5227198  -0.36247474  0.22250532]
 [ 0.65962941  2.25876959 -1.5141364   0.48092516  0.91414201]
 [-0.40514216  0.99761716 -0.6792819   0.28558544 -0.34801182]
 [-0.50027619 -1.02605408 -0.79312165 -0.26144444 -1.00967162]
 [-0.1684388  -0.58442695 -0.09309345  0.61722588  0.00838068]]


In [7]:
# Compute R.H.S of the Equation
resR = s * A + s * B
print(resR)

[[ 0.23092947 -0.45566922  0.73235297 -0.54789103  0.18954118]
 [-0.10380992  0.9350587  -0.22498698 -0.67292268 -0.33865129]
 [ 0.95555409  0.89876608 -0.5227198  -0.36247474  0.22250532]
 [ 0.65962941  2.25876959 -1.5141364   0.48092516  0.91414201]
 [-0.40514216  0.99761716 -0.6792819   0.28558544 -0.34801182]
 [-0.50027619 -1.02605408 -0.79312165 -0.26144444 -1.00967162]
 [-0.1684388  -0.58442695 -0.09309345  0.61722588  0.00838068]]


In [8]:
# Verify that L.H.S - R.H.S = 0 Matrix
print(resL - resR)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.77555756e-17]
 [-5.55111512e-17  0.00000000e+00  0.00000000e+00  0.00000000e+00
   5.55111512e-17]
 [ 0.00000000e+00  1.11022302e-16  0.00000000e+00  5.55111512e-17
  -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00 -2.22044605e-16  5.55111512e-17
   0.00000000e+00]
 [ 5.55111512e-17  0.00000000e+00  0.00000000e+00  5.55111512e-17
   0.00000000e+00]
 [ 1.11022302e-16  0.00000000e+00 -1.11022302e-16  0.00000000e+00
   2.22044605e-16]
 [-2.77555756e-17  0.00000000e+00  1.38777878e-17  0.00000000e+00
  -3.46944695e-18]]


This conforms our hypothesis that matrix-scalar multiplication is linear. That is, it obeys that distributive law.