### Outer Product of Vectors
The outer product of two vectors combines every element of one vector with every element of the other, producing a **matrix** rather than a single value.
Each entry of the resulting matrix is the product of one element from each vector:

$$
\mathbf{a}\mathbf{b}^{T}
=
\begin{bmatrix}
a_1b_1 & a_1b_2 & \cdots & a_1b_n\\
a_2b_1 & a_2b_2 & \cdots & a_2b_n\\
\vdots & \vdots & \ddots & \vdots\\
a_mb_1 & a_mb_2 & \cdots & a_mb_n
\end{bmatrix}
$$


In [1]:
# Import Numpy Module
import numpy as np

In [2]:
# Define two vectors
a = np.array([1, 2, 3, 4])
b = np.array([4, 1, -1])

In [3]:
# Method-1: Outer Product of 2 Vectors
abT = np.outer(a, b)
print(f"abT =\n{abT}")

abT =
[[ 4  1 -1]
 [ 8  2 -2]
 [12  3 -3]
 [16  4 -4]]


In [4]:
# Method-2: Outer Product of 2 Vectors
abT = np.zeros((len(a), len(b)))
for i in range(len(a)):
    for j in range(len(b)):
        abT[i,j] = a[i] * b[j]

print(f"abT =\n{abT}")

abT =
[[ 4.  1. -1.]
 [ 8.  2. -2.]
 [12.  3. -3.]
 [16.  4. -4.]]
