### Code Challenge - Dot Product with Matrix Columns
- Create 2 4x6 matrices of random numbers
- Use a for Loop to compute Dot Products between corresponding columns 

In [2]:
import numpy as np

In [4]:
A = np.random.randn(4,6)
B = np.random.randn(4,6)

print("A = ")
print(A)
print(' ')
print("B = ")
print(B)

A = 
[[ 1.28769684 -0.72772524 -1.3306284   0.87677997  0.80524225 -1.39245912]
 [-0.44550025  1.02747159  0.79716937 -1.06237236 -0.54977841 -0.96263047]
 [ 0.41951035 -0.09299625  1.61344505 -1.02447687  1.73737085  1.15337353]
 [-1.52066738  0.84830228 -1.74272548 -0.86336751 -0.52981532  0.11527583]]
 
B = 
[[ 0.48573822 -2.09659292 -0.61956657  0.97060116 -0.2881887   0.17114424]
 [-0.03475202 -0.20439169  0.69123696  0.46087994  1.69754597 -0.07530701]
 [ 0.0313474  -0.00714158  0.89798762 -1.23375698 -0.91959721  0.19706213]
 [ 1.64354056 -0.48942409  0.31016323 -0.08148016 -0.61223707 -0.99051796]]


In [11]:
# Compute Dot Products between corresponding columns of A and B
dot_products = np.zeros(A.shape[1])
for column in range(A.shape[1]):
    # print("D"+str(column), "= ", np.dot(A[:,column], B[:, column]))
    dot_products[column] = np.dot(A[:,column], B[:, column])

print("dot_products = ")
print(dot_products)

dot_products = 
[-1.84516235  0.9012215   2.28377013  1.69568035 -2.43864464 -0.05271506]
